//
// Trimmer Framework for Unity
// https://sttz.ch/trimmer
//

#if UNITY_EDITOR && TRIMMER_ADDRESSABLES

using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using sttz.Trimmer.BaseOptions;
using UnityEditor.Build.Reporting;
using UnityEditor.AddressableAssets.Settings;
using UnityEditor.AddressableAssets.Build;
using UnityEditor.AddressableAssets;
using UnityEditor.Build;
using UnityEditor;
using UnityEngine.AddressableAssets;
using IOPath = System.IO.Path;

namespace sttz.Trimmer.Options
{

/// <summary>
/// Option to build Addressables before a player build.
/// </summary>
/// <remarks>
/// The settings, profile id and data builder child options
/// can be left empty for the defaults to be used. Some of 
/// the options can be set to override the defaults, the 
/// option will try to revert any changes it has made.
/// </remarks>
[Capabilities(OptionCapabilities.ConfiguresBuild)]
public class OptionBuildAddressables : OptionToggle
{
    protected override void Configure()
    {
        Category = "Build";
    }

    /// <summary>
    /// Option to set the Addressable settings to use.
    /// </summary>
    /// <remarks>
    /// Defaults to the Addressables default settings object.
    /// </remarks>
    public class OptionSettings : OptionAsset<AddressableAssetSettings>
    {
        protected override void Configure()
        {
            DefaultValue = null;
        }
    }

    /// <summary>
    /// Option to select the Addressables profile (by id).
    /// </summary>
    /// <remarks>
    /// Defaults to the setting's active profile.
    /// </remarks>
    public class OptionProfileId : OptionString
    {
        protected override void Configure()
        {
            DefaultValue = "";
        }
    }

    /// <summary>
    /// Option to select the data builder script.
    /// </summary>
    /// <remarks>
    /// Defaults to the active player data builder. The builder object
    /// will be added to the settings object (the default if <see cref="OptionSettings"/>
    /// is not set) if it does not exist yet.
    /// </remarks>
    public class OptionDataBuilder : OptionAsset<ScriptableObject>
    {
        protected override void Configure()
        {
            DefaultValue = null;
        }
    }
    
    /// <summary>
    /// Option to enable output from <see cref="UnityEngine.AddressableAssets.Addressables.Log"/>
    /// and its cohorts at runtime,
    /// including in player builds.
    /// </summary>
    /// <remarks>
    /// This option sets the <c>ADDRESSABLES_LOG_ALL</c> compilation symbol.
    /// If it's defined by other means, this option will not remove it.
    /// </remarks>
    public class OptionEnableRuntimeLogging : OptionToggle
    {
        const string Symbol = "ADDRESSABLES_LOG_ALL";

        protected override void Configure()
        {
            DefaultValue = false;
        }

        public override void GetScriptingDefineSymbols(OptionInclusion inclusion, HashSet<string> symbols)
        {
            base.GetScriptingDefineSymbols(inclusion, symbols);

            if (Value)
                symbols.Add(Symbol);
        }
    }

    /// <summary>
    /// Option to clear intermediate data generated by the data builder script
    /// after the build finishes.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Calls the selected builder's <see cref="IDataBuilder.ClearCachedData"/> method
    /// when the Addressables build completes successfully or fails with an error.
    /// Defaults to <see langword="true"/>.
    /// Set this to <see langword="false"/> if you need to use the intermediate
    /// data for debugging or other reasons.
    /// </para>
    /// <para>
    /// Your implementation of <see cref="IDataBuilder.ClearCachedData"/>
    /// should not throw an exception.
    /// </para>
    /// </remarks>
    public class OptionClearIntermediateData : OptionToggle
    {
        protected override void Configure()
        {
            DefaultValue = true;
        }
    }

    /// <summary>
    /// Option to copy certain Addressables-related build logs into the output directory.
    /// </summary>
    /// <remarks>
    /// Addressables exposes a detailed timeline of its build process through
    /// a file located at <c>Library/com.unity.addressables/AddressablesBuildTEP.json</c>.
    /// This file is overwritten with each Addressables build,
    /// which can complicate analysis if your project involves multiple build profiles.
    /// This option, if enabled, will copy the aforementioned file
    /// to the location given by TODO
    /// </remarks>
    /// <seealso href="https://docs.unity3d.com/Packages/com.unity.addressables@1.21/manual/BuildProfileLog"/>
    public class OptionCopyBuildTimelineToOutputDirectory : OptionToggle
    {
        protected override void Configure()
        {
            DefaultValue = false;
        }
    }
    
    /// <summary>
    /// Option to copy certain Addressables-related build logs into the output directory.
    /// </summary>
    /// <remarks>
    /// Addressables exposes a detailed timeline of its build process through
    /// a file located at <c>Library/com.unity.addressables/AddressablesBuildTEP.json</c>.
    /// This file is overwritten with each Addressables build,
    /// which can complicate analysis if your project involves multiple build profiles.
    /// This option, if enabled, will copy the aforementioned file
    /// to the location given by TODO
    /// </remarks>
    /// <seealso href="https://docs.unity3d.com/Packages/com.unity.addressables@1.21/manual/BuildProfileLog"/>
    public class OptionCopyBuildLayoutToOutputDirectory : OptionToggle
    {
        protected override void Configure()
        {
            DefaultValue = false;
        }
    }

    override public BuildPlayerOptions PrepareBuild(BuildPlayerOptions options, OptionInclusion inclusion)
    {
        options = base.PrepareBuild(options, inclusion);

        if (Value) BuildAddressables();

        return options;
    }

    void BuildAddressables()
    {
        // Original values to restore overrides
        var originalSettings = AddressableAssetSettingsDefaultObject.Settings;
        string originalProfileId = null;
        int originalDataBuilderIndex = -1;

        var settings = originalSettings;
        var result = default(AddressablesPlayerBuildResult);
        try {
            // Apply overrides
            var settingsOption = GetChild<OptionSettings>();
            if (settingsOption.Value != null) {
                settings = AddressableAssetSettingsDefaultObject.Settings = settingsOption.Value;
            }

            if (settings == null) {
                throw new BuildFailedException($"OptionBuildAddressables: No Addressables Asset Settings object set and no default set either.");
            }

            var profileOption = GetChild<OptionProfileId>();
            if (!string.IsNullOrEmpty(profileOption.Value)) {
                originalProfileId = settings.activeProfileId;
                settings.activeProfileId = profileOption.Value;
            }

            var builderOption = GetChild<OptionDataBuilder>();
            if (builderOption.Value != null) {
                var index = settings.DataBuilders.IndexOf(builderOption.Value);
                if (index < 0) {
                    if (!settings.AddDataBuilder((IDataBuilder)builderOption.Value)) {
                        throw new Exception($"OptionBuildAddressables: Failed to add data builder to settings (builder = {builderOption.Value})");
                    }
                    index = settings.DataBuilders.Count - 1;
                }
                originalDataBuilderIndex = settings.ActivePlayerDataBuilderIndex;
                settings.ActivePlayerDataBuilderIndex = index;
            }

            // Build!
            AddressableAssetSettings.BuildPlayerContent(out result);

            if (GetChild<OptionCopyBuildTimelineToOutputDirectory>() is { Value: true }) {
                // Copy the build timeline to the output directory
                const string BuildTimelineFilename = "AddressablesBuildTEP.json"; 
                var buildLogLibraryPath = IOPath.Combine(Addressables.LibraryPath, BuildTimelineFilename);
                var localBuildPath = settings.profileSettings.GetValueByName(settings.activeProfileId, AddressableAssetSettings.kLocalBuildPath);
                var localBuildPathResolved = settings.profileSettings.EvaluateString(settings.activeProfileId, localBuildPath);
                var buildLogDataPath = IOPath.Combine(localBuildPathResolved, BuildTimelineFilename);
                File.Copy(buildLogLibraryPath, buildLogDataPath);
            }
            
            if (GetChild<OptionCopyBuildLayoutToOutputDirectory>() is { Value: true }) {
                // Copy the build timeline to the output directory
                const string BuildLayoutFilename = "buildlayout.txt"; 
                var buildLogLibraryPath = IOPath.Combine(Addressables.LibraryPath, BuildLayoutFilename);
                var localBuildPath = settings.profileSettings.GetValueByName(settings.activeProfileId, AddressableAssetSettings.kLocalBuildPath);
                var localBuildPathResolved = settings.profileSettings.EvaluateString(settings.activeProfileId, localBuildPath);
                var buildLogDataPath = IOPath.Combine(localBuildPathResolved, BuildLayoutFilename);
                File.Copy(buildLogLibraryPath, buildLogDataPath);
            }
        } finally {
            
            // Clear intermediate data and restore overrides
            if (settings != null) {
                // Clear intermediate data if requested
                if (GetChild<OptionClearIntermediateData>() is { Value: true }) {
                    settings.ActivePlayerDataBuilder?.ClearCachedData();
                }
                if (originalDataBuilderIndex >= 0) {
                    settings.ActivePlayerDataBuilderIndex = originalDataBuilderIndex;
                }
                if (originalProfileId != null) {
                    settings.activeProfileId = originalProfileId;
                }
            }
            AddressableAssetSettingsDefaultObject.Settings = originalSettings;
        }

        if (!string.IsNullOrEmpty(result.Error)) {
            throw new BuildFailedException("OptionBuildAddressables: Addressables build failed with error:\n" + result.Error);
        }

        Debug.Log($"Built {result.LocationCount} Addressable assets in {result.Duration}s to {result.OutputPath}");
    }
}

}

#endif
